fixes

diff --git a/.github/actions/config-access-point/action.yml b/.github/actions/config-access-point/action.yml
--- a/.github/actions/config-access-point/action.yml
+++ b/.github/actions/config-access-point/action.yml
@@ -21,16 +21,21 @@ runs:
         sudo mv dnsmasq /mnt/etc/dnsmasq.d
         sudo mv hostapd.conf /mnt/etc/hostapd
         sudo mv wlan0 /mnt/etc/network/interfaces.d
+        echo "delivery is done!"
+
         sudo chroot /mnt sudo sed -i 's/#net.ipv4.ip_forward=1/net.ipv4.ip_forward=1'
 
         ## setup the routing tables between wlan and ethernet ##
         sudo chroot /mnt sudo iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
         sudo chroot /mnt sudo iptables -A FORWARD -i eth0 -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT
         sudo chroot /mnt sudo iptables -A FORWARD -i wlan0 -o eth0 -j ACCEPT
+        echo "iptables is setted"
 
         ## save settings ##
         sudo chroot /mnt sh -c "iptables-save > /etc/iptables.ipv4.nat"
 
         sudo chroot /mnt ehco 'up iptables-restore < /etc/iptables.ipv4.nat' > /etc/network/interfaces.d/iptables
 
-        sudo chroot /mnt sudo systemctl enable hostapd dnsmasq
+        sudo chroot /mnt sh -c "systemctl enable hostapd" || { echo "an error occured while enabling hostapd";exit 1; }
+        sudo chroot /mnt sh -c "systemctl enable dnsmasq" || { echo "an error occured while enabling dnsmasq";exit 1; }
+        echo "config-access-point is done"
