Update build_image.yml

diff --git a/.github/workflows/build_image.yml b/.github/workflows/build_image.yml
--- a/.github/workflows/build_image.yml
+++ b/.github/workflows/build_image.yml
@@ -24,7 +24,7 @@ jobs:
         - name: Spawn rpi image
           run: |
             wget https://downloads.raspberrypi.com/raspios_lite_arm64/images/raspios_lite_arm64-2024-07-04/2024-07-04-raspios-bookworm-arm64-lite.img.xz
-            xz -dk *img.xz
+            xz -d *img.xz
             mv *img raspios.img
 
         - name: Install required packages # Установка необходимых утилит для работы с образом
@@ -41,6 +41,19 @@ jobs:
 
         - name: Copy qemu tools to mounted image 
           run: sudo cp /usr/bin/qemu-arm-static /mnt/usr/bin/
+
+        - name: Copy qemu tools to mounted image
+          run: |
+             if [ ! -f /usr/bin/qemu-arm-static ]; then
+              echo "qemu-arm-static not found on host system!"
+              exit 1
+             fi
+             sudo cp /usr/bin/qemu-arm-static /mnt/usr/bin/
+             ls -l /mnt/usr/bin/qemu-arm-static
+             if [ ! -f /mnt/usr/bin/qemu-arm-static ]; then
+              echo "qemu-arm-static not found in the image!"
+              exit 1
+             fi
 
         - name: Install file manager in the image # Установка файлового менеджера в образ
           run: |
